### ISSUE TITLE
Issues in the file selection dialog box (was: B.Jumblr doesn't show audio files, only directories, in its file selection dialog)

### ISSUE THREAD

**Issue by yurivict** [sjaehn/BJumblr#26] opened 2021-04-07 14:27 UTC

**Comment by sjaehn** [comment] 2021-04-07 18:06
It seems like everything is different in FreeBSD ;-). Once again I can't reproduce it on Ubuntu 20.04 and Manjaro.

Does it show any files (not only directories) if you switch to "All files"?

The only difference is the regex term used for the file names. There is no scanning the files themselves. Only their names. For "All files" its https://github.com/sjaehn/BJumblr/blob/063febe41cd34ab5c3a05f9b188cc432970aa622/src/BJumblrGUI.cpp#L2206 but for "Audio files" it's https://github.com/sjaehn/BJumblr/blob/063febe41cd34ab5c3a05f9b188cc432970aa622/src/BJumblrGUI.cpp#L2207

**Comment by yurivict** [comment] 2021-04-07 18:43
Sorry, I originally misunderstood how the file selection screen works. I assumed that files are supposed to be displayed in the right pane, but this pane in reality is reserved for details of audio file.

I would suggest that you would place a label in the right pane saying "No audio file selected" when it is currently blank.

Additionally, it doesn't seem to handle broken wav files properly.
The file ```five-1.wav``` is broken in some way. Yet, when the user clicks on it previous file's details are still shown.

Then, it would be better if the file name box on top was editable. Currently the user can't even delete/add characters in the end. Users are accustomed to editability because of similar Qt/Gtk file selection dialogs.


https://user-images.githubusercontent.com/271906/113917711-5f9dd580-9796-11eb-83e4-685240361917.mp4

**Comment by sjaehn** [comment] 2021-04-08 19:18
Still showing the previously selected sample was a bug. Fixed in aa09e6d4eeaaf8557b6778622e03a90c020f4328.

Showing a message like "No audio file selected" is a good idea. Thanks. Implemented in 67c53c7d68fef2e63a5a6c8691ebccc6c81b50ae.

**Comment by yurivict** [comment] 2021-04-08 19:26
When the file name has extension of an audio file but it can't be parsed you should also inform the user with a proper text in the right pane.

**Comment by sjaehn** [comment] 2021-04-09 16:49
You are right but I'll keep the present "No audio file selected" message. At least for this moment. By now this message is shown if libsndfile sf_open() returns NULL (or info.frames == 0) and I don't look up to sf_error(). Maybe in the future.

**Comment by sjaehn** [comment] 2021-04-12 16:32
Feature added in dc384021ecd26618c4b29ee9ab39d8ecb64a2f4b and 899229587367c4dd9fa17360f96012d8f6ee31b7 now shows error messages provided by libsndfile. There are two limitations. (i) Information from libsndfile is often limited to  "File contains data in an unknown format." (ii) The internationalization feature of B.Jumblr can't take care about the libsndfile output.

**Closed as completed** 2021-04-15 18:27 UTC
