### ISSUE TITLE
Sample not restored in Carla/NSM

### ISSUE THREAD

**Issue by grammoboy2** [sjaehn/BJumblr#21] opened 2020-11-09 21:50 UTC
Not sure whether this is a BJumblr bug or a Carla bug (cc @falkTX )
But when saving a session, closing and re-opening the session in NSM, the loaded sample in BJumblr isn't restored.

**Comment by falkTX** [comment] 2020-11-09 22:20
can you try outside of NSM? I think there is a bug related to path being used for plugins while under NSM (in Carla)

**Comment by grammoboy2** [comment] 2020-11-09 22:27
On 11/9/20 11:20 PM, Filipe Coelho wrote:
>
> can you try outside of NSM? I think there is a bug related to path 
> being used for plugins while under NSM (in Carla)
>
Looks like there is the same problem when using this plugin in Carla 
without NSM.
>

**Comment by falkTX** [comment] 2020-11-09 22:29
Update the carla project file here please. thanks. (I do not have the plugin packaged yet, so cant try right away)

**Comment by grammoboy2** [comment] 2020-11-09 22:33
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE CARLA-PROJECT>
<CARLA-PROJECT VERSION='2.2'>
 <EngineSettings>
  <ForceStereo>false</ForceStereo>
  <PreferPluginBridges>false</PreferPluginBridges>
  <PreferUiBridges>true</PreferUiBridges>
  <UIsAlwaysOnTop>false</UIsAlwaysOnTop>
  <MaxParameters>200</MaxParameters>
  <UIBridgesTimeout>4000</UIBridgesTimeout>
 </EngineSettings>

 <Transport>
  <BeatsPerMinute>120</BeatsPerMinute>
 </Transport>

 
 <Plugin>
  <Info>
   <Type>LV2</Type>
   <Name>B.Jumblr</Name>
   <URI>https://www.jahnichen.de/plugins/lv2/BJumblr</URI>
  </Info>

  <Data>
   <Active>Yes</Active>
   <ControlChannel>1</ControlChannel>
   <Options>0x3f0</Options>

   <Parameter>
    <Index>0</Index>
    <Name>Source</Name>
    <Symbol>source</Symbol>
    <Value>1</Value>
   </Parameter>

   <Parameter>
    <Index>1</Index>
    <Name>Play</Name>
    <Symbol>play</Symbol>
    <Value>1</Value>
   </Parameter>

   <Parameter>
    <Index>2</Index>
    <Name>Nr of steps</Name>
    <Symbol>nr_of_steps</Symbol>
    <Value>24</Value>
   </Parameter>

   <Parameter>
    <Index>3</Index>
    <Name>Step base</Name>
    <Symbol>stepbase</Symbol>
    <Value>1</Value>
   </Parameter>

   <Parameter>
    <Index>4</Index>
    <Name>Step size</Name>
    <Symbol>stepsize</Symbol>
    <Value>0.25</Value>
   </Parameter>

   <Parameter>
    <Index>5</Index>
    <Name>Step offset</Name>
    <Symbol>stepoffset</Symbol>
    <Value>1</Value>
   </Parameter>

   <Parameter>
    <Index>6</Index>
    <Name>Manual progression delay</Name>
    <Symbol>manual_progression_delay</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>7</Index>
    <Name>Speed</Name>
    <Symbol>speed</Symbol>
    <Value>1</Value>
   </Parameter>

   <Parameter>
    <Index>8</Index>
    <Name>Playback pattern page</Name>
    <Symbol>playback_page</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>9</Index>
    <Name>Page 1: MIDI status</Name>
    <Symbol>page_1_midi_status</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>10</Index>
    <Name>Page 1: MIDI channel</Name>
    <Symbol>page_1_midi_channel</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>11</Index>
    <Name>Page 1: MIDI note / message</Name>
    <Symbol>page_1_midi_message</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>12</Index>
    <Name>Page 1: MIDI value</Name>
    <Symbol>page_1_midi_value</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>13</Index>
    <Name>Page 2: MIDI status</Name>
    <Symbol>page_2_midi_status</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>14</Index>
    <Name>Page 2: MIDI channel</Name>
    <Symbol>page_2_midi_channel</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>15</Index>
    <Name>Page 2: MIDI note / message</Name>
    <Symbol>page_2_midi_message</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>16</Index>
    <Name>Page 2: MIDI value</Name>
    <Symbol>page_2_midi_value</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>17</Index>
    <Name>Page 3: MIDI status</Name>
    <Symbol>page_3_midi_status</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>18</Index>
    <Name>Page 3: MIDI channel</Name>
    <Symbol>page_3_midi_channel</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>19</Index>
    <Name>Page 3: MIDI note / message</Name>
    <Symbol>page_3_midi_message</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>20</Index>
    <Name>Page 3: MIDI value</Name>
    <Symbol>page_3_midi_value</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>21</Index>
    <Name>Page 4: MIDI status</Name>
    <Symbol>page_4_midi_status</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>22</Index>
    <Name>Page 4: MIDI channel</Name>
    <Symbol>page_4_midi_channel</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>23</Index>
    <Name>Page 4: MIDI note / message</Name>
    <Symbol>page_4_midi_message</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>24</Index>
    <Name>Page 4: MIDI value</Name>
    <Symbol>page_4_midi_value</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>25</Index>
    <Name>Page 5: MIDI status</Name>
    <Symbol>page_5_midi_status</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>26</Index>
    <Name>Page 5: MIDI channel</Name>
    <Symbol>page_5_midi_channel</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>27</Index>
    <Name>Page 5: MIDI note / message</Name>
    <Symbol>page_5_midi_message</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>28</Index>
    <Name>Page 5: MIDI value</Name>
    <Symbol>page_5_midi_value</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>29</Index>
    <Name>Page 6: MIDI status</Name>
    <Symbol>page_6_midi_status</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>30</Index>
    <Name>Page 6: MIDI channel</Name>
    <Symbol>page_6_midi_channel</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>31</Index>
    <Name>Page 6: MIDI note / message</Name>
    <Symbol>page_6_midi_message</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>32</Index>
    <Name>Page 6: MIDI value</Name>
    <Symbol>page_6_midi_value</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>33</Index>
    <Name>Page 7: MIDI status</Name>
    <Symbol>page_7_midi_status</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>34</Index>
    <Name>Page 7: MIDI channel</Name>
    <Symbol>page_7_midi_channel</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>35</Index>
    <Name>Page 7: MIDI note / message</Name>
    <Symbol>page_7_midi_message</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>36</Index>
    <Name>Page 7: MIDI value</Name>
    <Symbol>page_7_midi_value</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>37</Index>
    <Name>Page 8: MIDI status</Name>
    <Symbol>page_8_midi_status</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>38</Index>
    <Name>Page 8: MIDI channel</Name>
    <Symbol>page_8_midi_channel</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>39</Index>
    <Name>Page 8: MIDI note / message</Name>
    <Symbol>page_8_midi_message</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>40</Index>
    <Name>Page 8: MIDI value</Name>
    <Symbol>page_8_midi_value</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>41</Index>
    <Name>Page 9: MIDI status</Name>
    <Symbol>page_9_midi_status</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>42</Index>
    <Name>Page 9: MIDI channel</Name>
    <Symbol>page_9_midi_channel</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>43</Index>
    <Name>Page 9: MIDI note / message</Name>
    <Symbol>page_9_midi_message</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>44</Index>
    <Name>Page 9: MIDI value</Name>
    <Symbol>page_9_midi_value</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>45</Index>
    <Name>Page 10: MIDI status</Name>
    <Symbol>page_10_midi_status</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>46</Index>
    <Name>Page 10: MIDI channel</Name>
    <Symbol>page_10_midi_channel</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>47</Index>
    <Name>Page 10: MIDI note / message</Name>
    <Symbol>page_10_midi_message</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>48</Index>
    <Name>Page 10: MIDI value</Name>
    <Symbol>page_10_midi_value</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>49</Index>
    <Name>Page 11: MIDI status</Name>
    <Symbol>page_11_midi_status</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>50</Index>
    <Name>Page 11: MIDI channel</Name>
    <Symbol>page_11_midi_channel</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>51</Index>
    <Name>Page 11: MIDI note / message</Name>
    <Symbol>page_11_midi_message</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>52</Index>
    <Name>Page 11: MIDI value</Name>
    <Symbol>page_11_midi_value</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>53</Index>
    <Name>Page 12: MIDI status</Name>
    <Symbol>page_12_midi_status</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>54</Index>
    <Name>Page 12: MIDI channel</Name>
    <Symbol>page_12_midi_channel</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>55</Index>
    <Name>Page 12: MIDI note / message</Name>
    <Symbol>page_12_midi_message</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>56</Index>
    <Name>Page 12: MIDI value</Name>
    <Symbol>page_12_midi_value</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>57</Index>
    <Name>Page 13: MIDI status</Name>
    <Symbol>page_13_midi_status</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>58</Index>
    <Name>Page 13: MIDI channel</Name>
    <Symbol>page_13_midi_channel</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>59</Index>
    <Name>Page 13: MIDI note / message</Name>
    <Symbol>page_13_midi_message</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>60</Index>
    <Name>Page 13: MIDI value</Name>
    <Symbol>page_13_midi_value</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>61</Index>
    <Name>Page 14: MIDI status</Name>
    <Symbol>page_14_midi_status</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>62</Index>
    <Name>Page 14: MIDI channel</Name>
    <Symbol>page_14_midi_channel</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>63</Index>
    <Name>Page 14: MIDI note / message</Name>
    <Symbol>page_14_midi_message</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>64</Index>
    <Name>Page 14: MIDI value</Name>
    <Symbol>page_14_midi_value</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>65</Index>
    <Name>Page 15: MIDI status</Name>
    <Symbol>page_15_midi_status</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>66</Index>
    <Name>Page 15: MIDI channel</Name>
    <Symbol>page_15_midi_channel</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>67</Index>
    <Name>Page 15: MIDI note / message</Name>
    <Symbol>page_15_midi_message</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>68</Index>
    <Name>Page 15: MIDI value</Name>
    <Symbol>page_15_midi_value</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>69</Index>
    <Name>Page 16: MIDI status</Name>
    <Symbol>page_16_midi_status</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>70</Index>
    <Name>Page 16: MIDI channel</Name>
    <Symbol>page_16_midi_channel</Symbol>
    <Value>0</Value>
   </Parameter>

   <Parameter>
    <Index>71</Index>
    <Name>Page 16: MIDI note / message</Name>
    <Symbol>page_16_midi_message</Symbol>
    <Value>128</Value>
   </Parameter>

   <Parameter>
    <Index>72</Index>
    <Name>Page 16: MIDI value</Name>
    <Symbol>page_16_midi_value</Symbol>
    <Value>128</Value>
   </Parameter>

   <CustomData>
    <Type>http://lv2plug.in/ns/ext/atom#Int</Type>
    <Key>https://www.jahnichen.de/plugins/lv2/BJumblr#NOTIFYplaybackPage</Key>
    <Value>AAAAAA==</Value>
   </CustomData>

   <CustomData>
    <Type>http://lv2plug.in/ns/ext/atom#Int</Type>
    <Key>https://www.jahnichen.de/plugins/lv2/BJumblr#NOTIFYeditMode</Key>
    <Value>AAAAAA==</Value>
   </CustomData>

   <CustomData>
    <Type>http://lv2plug.in/ns/ext/atom#String</Type>
    <Key>https://www.jahnichen.de/plugins/lv2/BJumblr#STATEpad</Key>
    <Value>

Matrix data:
pg:0; id:0; lv:1.000000;
pg:0; id:33; lv:1.000000;
pg:0; id:66; lv:1.000000;
pg:0; id:99; lv:1.000000;
pg:0; id:132; lv:1.000000;
pg:0; id:165; lv:1.000000;
pg:0; id:198; lv:1.000000;
pg:0; id:231; lv:1.000000;
pg:0; id:264; lv:1.000000;
pg:0; id:297; lv:1.000000;
pg:0; id:330; lv:1.000000;
pg:0; id:363; lv:1.000000;
pg:0; id:396; lv:1.000000;
pg:0; id:429; lv:1.000000;
pg:0; id:462; lv:1.000000;
pg:0; id:495; lv:1.000000;
pg:0; id:528; lv:1.000000;
pg:0; id:561; lv:1.000000;
pg:0; id:594; lv:1.000000;
pg:0; id:627; lv:1.000000;
pg:0; id:660; lv:1.000000;
pg:0; id:693; lv:1.000000;
pg:0; id:726; lv:1.000000;
pg:0; id:759; lv:1.000000;
pg:0; id:792; lv:1.000000;
pg:0; id:825; lv:1.000000;
pg:0; id:858; lv:1.000000;
pg:0; id:891; lv:1.000000;
pg:0; id:924; lv:1.000000;
pg:0; id:957; lv:1.000000;
pg:0; id:990; lv:1.000000;
pg:0; id:1023; lv:1.000000;

    </Value>
   </CustomData>

   <CustomData>
    <Type>http://lv2plug.in/ns/ext/atom#Path</Type>
    <Key>https://www.jahnichen.de/plugins/lv2/BJumblr#NOTIFYsamplePath</Key>
    <Value>7037__yawfle__050816-chair-01.wav</Value>
   </CustomData>
  </Data>
 </Plugin>

 <ExternalPatchbay>
  <Connection>
   <Source>B.Jumblr:Audio Output 1</Source>
   <Target>system:playback_1</Target>
  </Connection>
  <Connection>
   <Source>B.Jumblr:Audio Output 2</Source>
   <Target>system:playback_2</Target>
  </Connection>
 </ExternalPatchbay>
</CARLA-PROJECT>

**Comment by grammoboy2** [comment] 2020-11-09 22:36
[Uploading bjump_file.zip…]()

**Comment by grammoboy2** [comment] 2020-11-09 22:39
[bjump_file.zip](https://github.com/sjaehn/BJumblr/files/5513669/bjump_file.zip)

**Comment by sjaehn** [comment] 2020-11-09 23:22
Line 595 Bjumbl3.carxp:
```
   <CustomData>
    <Type>http://lv2plug.in/ns/ext/atom#Path</Type>
    <Key>https://www.jahnichen.de/plugins/lv2/BJumblr#NOTIFYsamplePath</Key>
    <Value>7037__yawfle__050816-chair-01.wav</Value>
   </CustomData>
```

The file name is stored, I'll check B.Jumblr's restore method.

**Comment by sjaehn** [comment] 2020-11-10 21:24
Confirmed. It works with Ardour but not with Carla. Can't open the respective sample file in Carla (sf_open from libsndfile returns NULL). Somehow the plugin doesn't get access to the sample file.

Background information: The file path is stored using the LV2_STATE__mapPath feature and the abstract_path function in https://github.com/sjaehn/BJumblr/blob/master/src/BJumblr.cpp#L853 . And restored in https://github.com/sjaehn/BJumblr/blob/master/src/BJumblr.cpp#L904 .

**Comment by sjaehn** [comment] 2020-11-21 17:22
@falkTX It only works if I hack the full sample file path into the carxp file. BTW, I observed the same problem with plugins from other authors, including Fabla. It looks like Carla looks into the wrong directory to load files. I use Carla 2.3.0-alpha1.

**Comment by sjaehn** [comment] 2020-12-21 12:03
absolute_path() function was missing in retrieve(). Fixed in 65b923284b5312d8dd49fd43c95a994ac73bd399 . I hope this will also fix the Carla problem.

**Comment by falkTX** [comment] 2020-12-21 12:06
oh so this might not have been a carla issue after all?

**Comment by sjaehn** [comment] 2020-12-21 12:34
Probably. I haven't successfully tested it in Carla yet (Carla 2.3.0-alpha2 always crashes, I'll make a rollback). But still, the same problem occurred with Fabla. I'll take a look into its source code again.

**Comment by sjaehn** [comment] 2020-12-21 12:38
Just checked. HvH made the same mistake in Fabla. Stored using abstract_path() but not restored with absolute_path(): https://github.com/openAVproductions/openAV-Fabla/blob/master/dsp/fabla.cxx#L937

**Comment by falkTX** [comment] 2020-12-21 12:42
Maybe see https://github.com/lv2/lv2/blob/master/plugins/eg-sampler.lv2/sampler.c#L522 ?
This example plugin works perfectly from what I tested, and in several hosts too.

**Comment by sjaehn** [comment] 2020-12-21 17:34
Yes I've seen it before and it was the starting point to make the commit mentioned above. Before, I used the eg-sampler version from the LV2 book as reference ( https://lv2plug.in/book/#_sampler_c ). Without abstrac_path/absolute_path and without thread safe restore (therefore my question about this in the lv2 devel list). I wonder if @drobilla want's to update the book?

BTW, B.Jumblr works now with Carla. File path bug successfully fixed.

**Closed as completed** 2020-12-26 23:13 UTC
Labels: bug, help wanted
